name: anubis
version: 0.0.1
maintainer: Shao Cheng <astrohavoc@gmail.com>
copyright: (c) 2017 Shao Cheng
license: BSD3
github: TerrorJack/anubis

extra-source-files:
  - LICENSE
  - README.md

dependencies:
  - base
  - bytestring
  - Cabal
  - compact
  - containers
  - deepseq
  - directory
  - sbv
  - singletons
  - template-haskell

ghc-options: -Wall

library:
  source-dirs: src
  other-extensions:
    - DataKinds
    - DeriveTraversable
    - GADTs
    - KindSignatures
    - ParallelListComp
    - ScopedTypeVariables
    - StandaloneDeriving
    - TemplateHaskell
    - TypeFamilies
