name: anubis
version: 0.0.1
maintainer: Shao Cheng <astrohavoc@gmail.com>
copyright: (c) 2017 Shao Cheng
license: BSD3
github: TerrorJack/anubis

extra-source-files:
  - LICENSE

dependencies:
  - base
  - sbv

ghc-options: -Wall

library:
  source-dirs: src
